<a href="https://colab.research.google.com/github/RenteriaRaul/Doctorado-DCAG/blob/main/notebooks/sustax/01_sustax_data_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import sys
import os

sys.path.append(os.path.abspath("../.."))

from scripts.sustax.inventory import build_sustax_inventory, build_group_summary
from scripts.sustax.merge import build_long_total_from_inventory, build_by_scenario_total

# **Configuración**

In [11]:
RAW_DIR = "/content/drive/MyDrive/Doctorado /Probabilidad/Precipitación/Datos Sustax"
OUT_DIR = "/content/drive/MyDrive/Doctorado /Probabilidad/Precipitación/Datos Sustax/SUSTAX_TOTAL_MERGED"

# **Inventory**

In [12]:
inventory_df, bad_df = build_sustax_inventory(RAW_DIR)
group_summary = build_group_summary(inventory_df)

inventory_df.head()

,sustax_file,base_name,lat,lon,n_rows,n_cols,scenarios_detected,path
0,Sustax_ Manzanillo_LosReyes.csv,Sustax_ Manzanillo_LosReyes,18.9695,-104.0625,37256,3,"SSP434, SSP460, SSP585",/content/drive/MyDrive/Doctorado /Probabilidad...
1,Sustax_ Manzanillo_LosReyes3.csv,Sustax_ Manzanillo_LosReyes,18.9695,-104.0625,37256,3,"SSP126, SSP245, SSP370",/content/drive/MyDrive/Doctorado /Probabilidad...
2,Sustax_ Manzanillo_LosReyesSSP119.csv,Sustax_ Manzanillo_LosReyes,18.9695,-104.0625,37256,1,SSP119,/content/drive/MyDrive/Doctorado /Probabilidad...
3,Sustax_Cuautitlan.csv,Sustax_Cuautitlan,19.5316,-104.3438,37256,3,"SSP434, SSP460, SSP585",/content/drive/MyDrive/Doctorado /Probabilidad...
4,Sustax_Cuautitlan2.csv,Sustax_Cuautitlan,19.5316,-104.3438,37256,3,"SSP126, SSP245, SSP370",/content/drive/MyDrive/Doctorado /Probabilidad...

# **Export inventory**

In [13]:
from scripts.sustax.inventory import export_inventory_outputs

export_inventory_outputs(
    inventory_df,
    group_summary,
    OUT_DIR,
    bad_df
)

{'inventory_path': '/content/drive/MyDrive/Doctorado /Probabilidad/Precipitación/Datos Sustax/SUSTAX_TOTAL_MERGED/SUSTAX_raw_inventory.csv',
 'group_summary_path': '/content/drive/MyDrive/Doctorado /Probabilidad/Precipitación/Datos Sustax/SUSTAX_TOTAL_MERGED/SUSTAX_group_summary.csv',
 'bad_path': '/content/drive/MyDrive/Doctorado /Probabilidad/Precipitación/Datos Sustax/SUSTAX_TOTAL_MERGED/SUSTAX_inventory_errors.csv'}

# **Merge LONG**

In [14]:
LONG_TOTAL_DIR = os.path.join(OUT_DIR, "LONG_TOTAL")

merged_summary_df, _ = build_long_total_from_inventory(
    inventory_df,
    LONG_TOTAL_DIR
)

merged_summary_df.head()

,sustax_total,lat,lon,n_original_files,original_files,n_rows_merged,scenarios_merged,out_file
0,Sustax_ Manzanillo_LosReyesTotal,18.9695,-104.0625,3,Sustax_ Manzanillo_LosReyes.csv | Sustax_ Manz...,260792,"SSP119, SSP126, SSP245, SSP370, SSP434, SSP460...",/content/drive/MyDrive/Doctorado /Probabilidad...
1,Sustax_CuautitlanTotal,19.5316,-104.3438,3,Sustax_Cuautitlan.csv | Sustax_Cuautitlan2.csv...,260792,"SSP119, SSP126, SSP245, SSP370, SSP434, SSP460...",/content/drive/MyDrive/Doctorado /Probabilidad...
2,Sustax_ManzanilloTotal,18.9695,-104.3438,4,Sustax_Manzanillo.csv | Sustax_Manzanillo2.csv...,279420,"ERA5, SSP119, SSP126, SSP245, SSP370, SSP434, ...",/content/drive/MyDrive/Doctorado /Probabilidad...
3,Sustax_MexicoTotal,18.6885,-104.0625,1,Sustax_Mexico2.csv,55884,"ERA5, SSP245, SSP370",/content/drive/MyDrive/Doctorado /Probabilidad...
4,Sustax_MexicoTotal,18.9695,-104.6250,1,Sustax_Mexico.csv,55884,"ERA5, SSP245, SSP370",/content/drive/MyDrive/Doctorado /Probabilidad...

# **BY SCENARIO**

In [15]:
BYSCEN_TOTAL_DIR = os.path.join(OUT_DIR, "BY_SCENARIO_TOTAL")

byscen_summary_df, _ = build_by_scenario_total(
    LONG_TOTAL_DIR,
    BYSCEN_TOTAL_DIR
)

byscen_summary_df.head()

,sustax_total,lat,lon,n_scenarios_generated,scenarios_generated
0,Sustax_ Manzanillo_LosReyesTotal,18.9695,-104.0625,7,Sustax_ Manzanillo_LosReyesTotal__SSP119__mm.c...
1,Sustax_CuautitlanTotal,19.5316,-104.3438,7,Sustax_CuautitlanTotal__SSP119__mm.csv | Susta...
2,Sustax_ManzanilloTotal,18.9695,-104.3438,8,Sustax_ManzanilloTotal__ERA5__mm.csv | Sustax_...
3,Sustax_MexicoTotal,18.9695,-104.6250,3,Sustax_MexicoTotal__ERA5__mm.csv | Sustax_Mexi...
4,Sustax_MinatitlanTotal,19.2506,-104.0625,8,Sustax_MinatitlanTotal__ERA5__mm.csv | Sustax_...